# Generated by Django 5.0.3 on 2026-02-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_paid',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_status',
            field=models.CharField(default='not_paid', max_length=8),
        ),
    ]
