# Generated by Django 5.0.3 on 2026-02-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_has_paid_profile_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialvideo',
            old_name='url',
            new_name='video_id',
        ),
        migrations.AddField(
            model_name='tutorialvideo',
            name='cover_image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
