# Generated by Django 5.0.3 on 2026-02-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_url_tutorialvideo_video_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialvideo',
            name='cover_image',
        ),
    ]
