# Generated by Django 5.0.3 on 2026-02-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_tutorialvideo_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default='2011-04-25'),
            preserve_default=False,
        ),
    ]
